#!/bin/bash

# 1. build backend (fork process)
./build-back &

# 2. build frontend (fork process)
./build-front &

# 3. wait for join processes
wait

# 4. open browser 
firefox http://localhost:4200/ &

# 5. run app
sudo docker-compose down --volumes
sudo docker-compose up --build

# 6. remove dangling containers
sudo docker system prune -f
