name: CI
on:
  push:
    paths:
    - 'pedibus/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Start Build
      run: |
        cd pedibus
        ./app-dock2
